public enum ScreenType
{
    GameStartScreeen,
    HomeScreen,
    MapScreen,
    ShopScreen,
    SettingsScreen,
    InfoScreen,
    FreeCoinsScreen,
    DailyStreakScreen,
    GamePlay,
    GameOver,
    LevelCompleted,
    BuyUndoScreen,
    BuyShuffleScreen,
    BuyMagicScreen,
    CountryInfoScreen,
    ContinueGame,
}